export const questionData: {category: string, type: string, difficulty: string, question: string, correctAnswer: string, incorrectAnswers: string}[] = [
    {
        category: "Science: Computers",
        type: "boolean",
        difficulty: "medium",
        question: "The HTML5 standard was published in 2014.",
        correctAnswer: "True",
        incorrectAnswers: "False",
    },
    {
        category: "Science: Computers",
        type: "boolean",
        difficulty: "medium",
        question: "The first computer bug was formed by faulty wires.",
        correctAnswer: "False",
        incorrectAnswers: "True",
    },
    {
        category: "Science: Computers",
        type: "boolean",
        difficulty: "medium",
        question: "FLAC stands for 'Free Lossless Audio Condenser'.",
        correctAnswer: "False",
        incorrectAnswers: "True",
    },
    {
        category: "Science: Computers",
        type: "boolean",
        difficulty: "medium",
        question: "All program codes have to be compiled into an executable file in order to be run. This file can then be executd on any machine.",
        correctAnswer: "False",
        incorrectAnswers: "True",

    },
    {
        category: "Science: Computers",
        type: "boolean",
        difficulty: "easy",
        question: "Linus Torvalds created Linux and Git.",
        correctAnswer: "True",
        incorrectAnswers: "False",
    },
    {
        category: "Science: Computers",
        type: "boolean",
        difficulty: "easy",
        question: "The programming language 'Python' is based off a modified version of 'JavaScript'",
        correctAnswer: "False",
        incorrectAnswers: "True",
    },
    {
        category: "Science: Computers",
        type: "boolean",
        difficulty: "medium",
        question: "AMD created the first consumer 64-bit processor.",
        correctAnswer: "True",
        incorrectAnswers: "False",
    },
    {
        category: "Science: Computers",
        type: "boolean",
        difficulty: "easy",
        question: "'HTML' stands for Hypertext Markup Language.",
        correctAnswer: "True",
        incorrectAnswers: "False",
    },
    {
        category: "Science: Computers",
        type: "boolean",
        difficulty: "easy",
        question: "In most programming languages, the operator ++ is equivalent to the statement '+= 1'.",
        correctAnswer: "True",
        incorrectAnswers: "False",
    },
    {
        category: "Science: Computers",
        type: "boolean",
        difficulty: "hard",
        question: "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
        correctAnswer: "False",
        incorrectAnswers: "True",
    }
];
